### ISSUE TITLE
feat: Adjust time format of calls saved in DynamoDB

### ISSUE THREAD

**Issue by edgarsilva948** [aws-samples/amazon-chime-sdk-meeting-summarizer#18]
### Describe the feature

Currently, the format being used is in epoch format. It needs adjustment to improve the UX.

### Use Case

It's very hard to identify the calls with this date format.

### Proposed Solution

change [this line](https://github.com/aws-samples/amazon-chime-sdk-meeting-summarizer/blob/45485f31b5e1f82e8d77555ab84d6710e775003d/src/resources/requestProcessor/utils.ts#L85).

### Acknowledgements

- [ ] I may be able to implement this feature request.

### CDK version used.

2.133.0

### Node.js Version

v20.11.1

### Environment details (OS name and version, etc.).

MacOS Sonoma 14.3.1

**Comment by aneumiller** [comment]
Discussed with Edgar. Resolved to use another column to the dynamo db table for display on the front end that is already formatted.
