### ISSUE TITLE
feat: Add MP3 link to DynamoDB for frontend use

### ISSUE THREAD

**Issue by edgarsilva948** [aws-samples/amazon-chime-sdk-meeting-summarizer#19]
### Describe the feature

there's a need to enhance the dynamodb table by adding a new column that will store the mp3 link, sourced from an s3 bucket. this link will be utilized in the frontend.

### Use Case

Its a prereq for the media player component to be created.

### Acknowledgements

- [ ] I may be able to implement this feature request.

### CDK version used.

2.133.0

### Node.js Version

v20.11.0

### Environment details (OS name and version, etc.).

MacOS Sonoma 14.3.1

**Comment by aneumiller** [comment]
Done
