### ISSUE TITLE
feat: extract meeting name/region from Invite and save to DynamoDB

### ISSUE THREAD

**Issue by edgarsilva948** [aws-samples/amazon-chime-sdk-meeting-summarizer#20]
### Describe the feature

the amazon chime sdk meeting summarizer app currently receives an invite containing the meeting information. there is a need to enhance the app by extracting the meeting name and region from the invite and saving it to dynamodb. this will allow for the meeting name/region to be made available in the frontend, along with the organizer details.

### Use Case

It would be great to have this info available in the front.

### Acknowledgements

- [ ] I may be able to implement this feature request.

### CDK version used.

2.133.0

### Node.js Version

v20.11.0

### Environment details (OS name and version, etc.).

MacOS Sonoma 14.3.1

**Comment by aneumiller** [comment]
Not needed.
