### ISSUE TITLE
feat: Add UUID to DynamoDB table to prevent ID conflicts

### ISSUE THREAD

**Issue by edgarsilva948** [aws-samples/amazon-chime-sdk-meeting-summarizer#21]
### Describe the feature

currently, the dynamodb table used in the amazon chime sdk meeting summarizer app defines call_id as the partition key and scheduled_time as the sort key. to enhance data integrity and avoid potential id conflicts, there is a need to introduce a universally unique identifier (uuid) for each entry in the table.

### Use Case

when changing the time format [here](https://github.com/aws-samples/amazon-chime-sdk-meeting-summarizer/issues/18), we will increase the chance to have conflicts.

### Acknowledgements

- [ ] I may be able to implement this feature request.

### CDK version used.

2.133.0

### Node.js Version

v20.11.1

### Environment details (OS name and version, etc.).

MacOS Sonoma 14.3.1

**Comment by aneumiller** [comment]
Discussed. Not necessary.
