### ISSUE TITLE
 feat: Enhance callSummary prompt for multilingual summary generation

### ISSUE THREAD

**Issue by edgarsilva948** [aws-samples/amazon-chime-sdk-meeting-summarizer#31]
### Describe the feature

currently the callSummary function generates summaries predominantly in English. to cater to a diverse user base and enhance global usability, there is a need to adjust this component to support summary generation in multiple languages.

### Use Case

to make the meeting summarizer more accessible and useful for non-English speakers or multilingual meetings.

### Acknowledgements

- [ ] I may be able to implement this feature request.

### CDK version used.

2.133.0

### Node.js Version

v20.11.1

### Environment details (OS name and version, etc.).

MacOS Sonoma 14.3.1

**Comment by aneumiller** [comment]
Done
